name: Test Package Compatibility on Windows on ARM

on: push

permissions:
  contents: read

jobs:
  check-python-compatibility:
    name: Check Compatibility with Python versions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-11-arm ]
        python-version: ['3.10', '3.11', '3.12', '3.13', 'pypy3.10'] #Python3.9 is unsupported on Windows on Arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: | 
          python -m pip install --pre -U pip
          python -m ensurepip

      - name: Install dependencies
        run: |
          python -m pip install -U pygame-ce

      - name: Install package
        run: |
          python -m pip install -e .
        

      - name: Import PGAA
        run: |
          python -c "import PGAA; print(PGAA.__version__)"
