name: Test Package Compatibility on MacOS (Intel and Apple Silicon)

on: push

permissions:
  contents: read

jobs:
  check-python-compatibility:
    name: Check Compatibility with Python versions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-15, macos-13 ]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', 'pypy3.10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Update pip
        run: |
          python -m pip install --pre -U pip
          python -m ensurepip

      - name: Install package with dependencies
        run: |
          python -m pip install -e .
        

      - name: Import PGAA
        run: |
          python -c "import pygame; pygame.init(); import PGAA; print(PGAA.__version__)"